apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: calculator-cli-deploy
  labels:
    app: calculator
spec:
  selector:
    matchLabels:
      app: calculator
  replicas: 3
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator-cli
        image: rfashwal/calculator-cli
        imagePullPolicy: Never
        ports:
        - name: cal-cliservice
          containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: cal-cliservice
spec:
  selector:
    app: calculator
  ports:
  - port: 9001
    targetPort: cal-cliservice
