piVersion: apps/v1beta1
kind: Deployment
metadata:
  name: calculator-service-deployment
  labels:
    app: calculator
spec:
  selector:
    matchLabels:
      app: calculator
  replicas: 3
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calc-service
        image: rfashwal/calculator-service
        imagePullPolicy: IfNotPresent
        ports:
        - name: calc-service
          containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: calc-service
spec:
  selector:
    app: calculator
  ports:
  - port: 9001
    targetPort: calc-service
